// Everything you give Sofhia lives here. Keep IDs unique and stable; order is
// exactly the order below. Set audio: '' for an unfinished / locked song.
export const ALBUM = {
  title: "Sofhia's Songs",
  subtitle: 'made you something hehe',
  openingHeading: 'HAPPY 16TH, SOFIII ♡',
  openingHint: 'go onnn, open it HAHAHA ♡',
  signature: '- fejee ♡',
  noteTitle: 'a little note for sofiii ♡',
  note: [
    'hii sofiii hehe',
    'sooo, i made you this little album for your birthday 😭',
    'these are just some songs that reminded me of you at some point. some of them i used to sing along to for fun, and some just kinda stuck with me HAHAHA.',
    'i never really planned on sharing all of this, but since it’s your birthday, i thought why not?',
    'idkk, i just wanted you to have something i actually made myself.',
    'happy 16th birthday, sofiii ♡',
    'hope you like it hehe',
  ],
  playerInvitation: 'PICK A SONG SOFIII HEHE',
  waitingTitle: 'pick oneee hehe ♡',
  waitingDetail: "i wonder which one you'll play first HAHAHA",
  tracklistCaption: 'some songs i wanted you to hear hehe ♡',
  albumPath: '/sofhias-songs-67',
  returnButtonText: 'my little album 💿♡',
  artist: 'Feje',
  closingMessage: '',
  entryButtonText: '🎵 I made you an album — tap to open',
  birthdayPath: '/sofhia-franchesca-16',
  cover: '/assets/album/cover.svg',
  frontCover: '/assets/album/sofhia-birthday-disc.jpg',
  idleCover: '/assets/album/feje-birthday-photo.jpg',
  mediaCover: '/assets/album/cover.png',
  backgroundMusic: '/assets/album/background.mp3',
  backgroundVolume: 0.4,
  loopCrossfade: 0.5,
  // A short original sample primes the same HTML audio element on OPEN ITT.
  // Do not replace this with a real song: priming is inaudible.
  unlockAudio: '/assets/album/sample.mp3',
  tracks: [
    { id: 'song-01', title: 'Song 01', audio: '/assets/album/sample.mp3', fallbackAudio: '/assets/album/sample.m4a', cover: '/assets/album/heart.svg', duration: 8, placeholder: true, note: '♡' },
    { id: 'song-02', title: 'Song 02', audio: '/assets/album/sample.mp3', fallbackAudio: '/assets/album/sample.m4a', cover: '/assets/album/star.svg', duration: 8, placeholder: true },
    { id: 'song-03', title: 'Song 03', audio: '/assets/album/sample.mp3', fallbackAudio: '/assets/album/sample.m4a', cover: '/assets/album/blossom.svg', placeholder: true },
    { id: 'song-04', title: 'Song 04', audio: '/assets/album/sample.mp3', fallbackAudio: '/assets/album/sample.m4a', cover: '/assets/album/star.svg', duration: 8, placeholder: true },
    { id: 'song-05', title: 'Song 05', audio: '/assets/album/sample.mp3', fallbackAudio: '/assets/album/sample.m4a', cover: '/assets/album/blossom.svg', duration: 8, placeholder: true, note: '♡' },
    { id: 'song-06', title: 'Song 06', audio: '/assets/album/sample.mp3', fallbackAudio: '/assets/album/sample.m4a', cover: '/assets/album/heart.svg', duration: 8, placeholder: true },
    { id: 'song-07', title: 'Song 07', audio: '/assets/album/sample.mp3', fallbackAudio: '/assets/album/sample.m4a', cover: '/assets/album/blossom.svg', placeholder: true },
    { id: 'song-08', title: 'Song 08', audio: '/assets/album/sample.mp3', fallbackAudio: '/assets/album/sample.m4a', cover: '/assets/album/heart.svg', duration: 8, placeholder: true },
    { id: 'song-09', title: 'Song 09', audio: '/assets/album/sample.mp3', fallbackAudio: '/assets/album/sample.m4a', cover: '/assets/album/star.svg', duration: 8, placeholder: true },
    { id: 'song-10', title: 'Song 10', audio: '/assets/album/sample.mp3', fallbackAudio: '/assets/album/sample.m4a', cover: '/assets/album/heart.svg', duration: 8, placeholder: true, lyrics: '♡' },
    { id: 'song-11', title: 'Song 11', audio: '/assets/album/sample.mp3', fallbackAudio: '/assets/album/sample.m4a', cover: '/assets/album/star.svg', duration: 8, placeholder: true },
    { id: 'song-12', title: 'Song 12', audio: '/assets/album/sample.mp3', fallbackAudio: '/assets/album/sample.m4a', cover: '/assets/album/blossom.svg', duration: 8, placeholder: true },
    { id: 'song-13', title: 'Song 13', audio: '/assets/album/sample.mp3', fallbackAudio: '/assets/album/sample.m4a', cover: '/assets/album/star.svg', placeholder: true },
    { id: 'song-14', title: 'Song 14', audio: '/assets/album/sample.mp3', fallbackAudio: '/assets/album/sample.m4a', cover: '/assets/album/blossom.svg', duration: 8, placeholder: true },
    { id: 'song-15', title: 'Song 15', audio: '/assets/album/sample.mp3', fallbackAudio: '/assets/album/sample.m4a', cover: '/assets/album/heart.svg', duration: 8, placeholder: true },
    { id: 'song-16', title: 'Song 16', audio: '/assets/album/sample.mp3', fallbackAudio: '/assets/album/sample.m4a', cover: '/assets/album/blossom.svg', duration: 8, placeholder: true },
    { id: 'song-17', title: 'Song 17', audio: '/assets/album/sample.mp3', fallbackAudio: '/assets/album/sample.m4a', cover: '/assets/album/heart.svg', duration: 8, placeholder: true },
    { id: 'song-18', title: 'Song 18', audio: '/assets/album/sample.mp3', fallbackAudio: '/assets/album/sample.m4a', cover: '/assets/album/star.svg', duration: 8, placeholder: true, note: '♡' },
  ],
};
